name: Analyze with CodeGuru Reviewer

on:
  - push
  - workflow_dispatch # This allows manual triggering of the action through the GitHub UI.

env:
  BUCKET_NAME: "codeguru-reviewer-fengfeng"
  AWS_REGION: "ap-southeast-2"

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  build:
    name: Analyze with CodeGuru Reviewer
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials for China region audience
        continue-on-error: true
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::692859905114:role/GitHub_identity_provider

      - uses: actions/checkout@v4
        if: ${{ always() }}
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        if: ${{ always() }}
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build project
        if: ${{ always() }}
        run: mvn compile -DskipTests

      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        if: ${{ always() }}
        continue-on-error: false
        with:
          s3_bucket: codeguru-reviewer-fengfeng
          build_path: ./target/classes

      - name: Store SARIF file
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: SARIF_recommendations
          path: ./codeguru-results.sarif.json

      - name: Upload review result
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeguru-results.sarif.json
