name: Analyze with CodeGuru Reviewer

on: 
  - push
  - workflow_dispatch # This allows manual triggering of the action through the GitHub UI.

permissions:
  id-token: write
  contents: read
  security-events: write 

jobs:
  build:
    name: Analyze with CodeGuru Reviewer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:

          aws-region: us-east-1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'

      - name: Build project
        run: mvn compile -DskipTests

      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          s3_bucket: codeguru-reviewer-github-profiler-demo-048169001733-uw2
          build_path: ./target/classes

      - name: Store SARIF file
        uses: actions/upload-artifact@v3 # Updated to v3
        with:
          name: SARIF_recommendations
          path: ./codeguru-results.sarif.json

      - name: Upload review result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeguru-results.sarif.json
